### ISSUE TITLE
CSS problemi

### ISSUE THREAD

**Issue by samirkarimov** [Pervinb/PragmatechFoundationProject#2]
![Screenshot_5](https://user-images.githubusercontent.com/24611841/102400457-68a64380-3ffb-11eb-93ac-9a59145f1376.jpg)
CSS faylinda ciddi problem var bu formada gorunur layihe onu fix ele suretle ki geri galan problemlere baxabilek

**Comment by Pervinb** [comment]
Məllim axşaminız xeyir,  bunu bilmirəm necə fix edim,bunu duzəldə
bilsəydim,məsələn header -in kodlarin codepen.io saytinda yaziram normal
gorsənirdi,VSCode-de yazdim,alt-alta falan dusdu,o birilərdə bunun
kimi,problem çoxdu ,məsələn "li" tagindən noqtələri yigmaq ucun kodu
yaziram "codepende" işləyir burda yox,sonea "a" larda altdan xətt və göy
rəngli yazilari silmək ucun kod yaziram,gedmir,sütunlar yan yana olmaqdan
alt alta olur,səhvidə tapmiramki duzəldimki,sonra qalan işləri sürərlə
görüm.
Vaxtinız olsa baxarsiniz mənim gormədiyim səhvləri görə bildiniz bəlkə
Təşəkkürlər

**Comment by samirkarimov** [comment]
senin yazdigin css fayllarini gormurem Pervin ona gore baxabilmirem ki hardadi senin sehvin sass papkasi goymusan amma o da menim yazdigim kodlardi senin oz yazdigin kodlar yoxdur orda.

**Comment by Pervinb** [comment]
Mellim bu issueni close ede bilersiniz
