### ISSUE TITLE
Daxili sehifeler

### ISSUE THREAD

**Issue by samirkarimov** [Pervinb/PragmatechFoundationProject#4]
- [ ] Mehsul sehifesi
- [ ] Kategoriya sehifesi
- [ ] Sifaris verme bolmesi
- [ ] Sebet sehifesi

Pervin bu sehifeleri ne vaxta tehvil verebilersen onu geyd ele

**Comment by Pervinb** [comment]
Salam,mellim en geci hefte sonuna qeder tehvil verecem

**Comment by samirkarimov** [comment]
gozleyecem Pervin
